# CONFIG FILE FOR AN EXPERIMENT
data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/semantic_processing/metadata/gp_words_metadata_train_valid_ft_29k.tsv'
model_save_dir: '/semantic_processing/inprogress_models/'
embedding_file: '/semantic_processing/metadata/fasttext/ft_embeddings_cs.p'
seed: 1248 #1358
language_set: 'CZE' # 'DEU' ' CZE'
dev_split: 'DEV' #DEV' #EVA
#sample_size: 30000
experiment_name: 'AWEs_1cnn_4rnn_biphon_1024D'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000
#
acoustic_encoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 1024
    n_layers: 1
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
phonetic_decoder:
    embedding_dim: 128
    hidden_state_dim: 1024
    n_layers: 1
#

training_hyperparams:
    alpha: 0.8 
    beta: 1.0
    learning_rate: 0.001
    batch_size: 256
    num_epochs: 100
    early_stopping_criteria: 10
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
