# CONFIG FILE FOR AN EXPERIMENT
data_dir: '/data/GP_FBANK_ALL_39/'
#speech_metadata: '/semantic_processing/metadata/gp_words_metadata_train_valid_ft_29k.tsv'
speech_metadata: '/semantic_processing/metadata/gp_words_metadata_new_splits_29k.tsv'
model_save_dir: '/semantic_processing/inprogress_models/'
embedding_file: '/semantic_processing/metadata/fasttext/ft_embeddings_pt.p'
seed: 42 #1248 #1358
language_set: 'POR' # 'DEU' ' CZE' 'POL'
dev_split: 'DEV' #DEV' #EVA
#sample_size: 30000
experiment_name: 'AWEs_1cnn_3rnn_phon_512D_a0_b1'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000
#
acoustic_encoder:
    encoder_arch: 'GRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 512
    n_layers: 3
    unit_dropout_prob: 0.1
    frame_dropout: True # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
phonetic_decoder:
    embedding_dim: 128
    hidden_state_dim: 512
    n_layers: 1
#

shuffle_semantic_vectors: True #False #

binarize_semantic_vectors: False #False

training_hyperparams:
    alpha: 0.0
    beta: 1.0 #0.0142857 #0.00508469 #1.0 #.01 #.0 #0.0142857 #0.0061 #0.0008487 # 1.0 #
    learning_rate: 0.001
    batch_size: 256
    num_epochs: 100
    early_stopping_criteria: 10
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
